### ISSUE TITLE
UI localization

### ISSUE THREAD

**Issue by chekoopa** [pythonInRelay/ao#15]
**Is your feature request related to a problem? Please describe.**
Microsoft To-Do is translated to many languages and somehow picks your language from profile settings. But Ao-specific menu and toolbars are still English, and it breaks immersion a little, even considering small amount of text to be translated.

**Describe the solution you'd like**
Add l18n support for menu bar and dialogs. Language selection could be system-based for the beginning, but actually it should be better to also let user to select it in some menu.

There's a plenty of l18n libraries and frameworks around, so it shouldn't be so difficult, and it also enables more user contributions with translation PRs.

**Comment by pythonInRelay** [comment]
Not an issue. Closing.

**Comment by chekoopa** [comment]
Sure it's not a critical issue, but a improvement request willing for someone's PR. It's kinda reckless to close it with such a line imho.
