### ISSUE TITLE
Describe installation instructions in README

### ISSUE THREAD

**Issue by gordeyg** [pythonInRelay/ao#17]
Happy to see you care about the project.  
Wanted yo use this fork but found no installation instructions while original one can be installed using snap.  
Not a web dev, so have no idea how to do it manually.

**Comment by chekoopa** [comment]
Instructions are listed in Releases (https://github.com/pythonInRelay/ao/releases/tag/7.0), there you can find how to build snap package (yet you'll have to watch some YouTube videos at this moment). 

If you got this working and want to contibute to the project, consider writing PR with full instructions. 

FYI, I use Nix, it builds just with `nix-build` (simply build a package) or `nix-env -if .` (to install into userspace).

**Comment by gordeyg** [comment]
Cool, thanks. I'll give it try
