### ISSUE TITLE
What would we do with Outlook apps inside Ao? (Outlook footer bar)

### ISSUE THREAD

**Issue by chekoopa** [pythonInRelay/ao#18]
**Is your feature request related to a problem? Please describe.**
Microsoft have updated To-Do app, intergrating it with Outlook suite, so the footer bar (`.sidebar-footer`) is shown to switch between Mail, Calendar, People, Files and Tasks (which To-Do took place of).

The problem is we can click a button and switch to other app, being inside of Ao. Thus, existing hotkeys are rendered useless, so the app itself is.

**Describe the solution you'd like**
There are some ways to implement it.

1. Just hide it, using CSS rule or JS code. The easiest.
2. Somehow filter link presses which lead away from `to-do.live.com` and perform `shell.openExternal` instead.
3. Transform Ao from To-Do client to Outlook suite wrapper. The hardest and needs a new repo.

**Comment by pythonInRelay** [comment]
I'll try and have a look at this in the next few days. Been really busy so far.

**Comment by chekoopa** [comment]
Bumping and leaving the custom rule for solution 1 here:

`.sidebar-footer { display: none; }`

**Comment by pythonInRelay** [comment]
Hi, I have been really busy with work. You can submit the PR yourself and I will accept it.
